export const apps = [
  {
    id: "qwerty",
    title: "Qwerty",
    subtitle: "沉浸式背单词 / 词库",
    blurb: "练单词、练节奏、练专注。",
    href: "/apps/qwerty",
  },
  {
    id: "sentences",
    title: "句库",
    subtitle: "句子收藏与练习",
    blurb: "把你想背的句子收起来。",
    href: "/apps/sentences",
  },
  {
    id: "calc",
    title: "随手算",
    subtitle: "快速计算器",
    blurb: "表达式直接算，支持括号与百分比。",
    href: "/apps/calc",
  },
  {
    id: "convert",
    title: "单位换算",
    subtitle: "长度 / 重量 / 温度",
    blurb: "常用单位一键换算。",
    href: "/apps/convert",
  },
  {
    id: "timer",
    title: "计时器",
    subtitle: "专注 / 倒计时",
    blurb: "一个干净的专注计时器。",
    href: "/apps/timer",
  },
  {
    id: "countdown",
    title: "倒计日",
    subtitle: "事件倒计时",
    blurb: "记录重要日期，自动计算剩余天数。",
    href: "/apps/countdown",
  },
  {
    id: "clipboard",
    title: "剪贴板",
    subtitle: "常用片段管理",
    blurb: "把常用文本放进收藏夹。",
    href: "/apps/clipboard",
  },
  {
    id: "formatter",
    title: "格式化",
    subtitle: "JSON 格式化 / 压缩",
    blurb: "粘贴即用。",
    href: "/apps/formatter",
  },
  {
    id: "notes",
    title: "记事",
    subtitle: "轻量 memo",
    blurb: "快速写点东西，自动保存。",
    href: "/apps/notes",
  },
];
